### ISSUE TITLE
Costs algorithm is too expensive

### ISSUE THREAD

**Issue by orthecreedence** [basisproject/tracker#39]
This closes #38. Essentially, when we add more orders, we need to pull out those orders and run them through the cost algo. This happens whenever an order is created/modified or a labor record is finalized. This is obviously backing things up.

----

Ok, an update (but keeping the notes below): this is definitely caused when pulling out rolling indexed objects. It gets worse over time as more items are added to the lists. Originally, the indexes just stored IDs and the main objects were pulled from there. However, to speed things up we duplicated the objects in the index itself so there's no need for a second lookup. While this saved about 3x the runtime cost, it doesnt buy us enough to fix the problem (even on a small scale economy).

Note that this affects three main objects:

- incoming orders
- outgoing orders
- labor records

What I'm realizing is it may be possible to store approximate averages of the sums of these values such that they don't need to be *extracted* each time, however this is starting to go down the road of optimizing for our *specific* costs algorithm, which I'm trying to avoid because it's going to change (probably).

So the question is: can we optimize the storage of aggregates of our cost values, on a per-company basis, in a generic enough way that are data is not *shaped* to our current costs algo?

I'm thinking something along these lines:

- Given the last period X (X being a year for example):
  - Store a sum of all labor hours
  - Store a sum of costs by type: operating/inventory/etc
  - Store a sum of the product outputs
  - For each sum-bucket, store the number of items included in that sum

For example, instead of storing X, Y, and Z separately, we store (X + Y + Z) and 3 as our final count of stored objects.

Implementation:

- When a new object is added to a rolling index we should have two callbacks:
  - One called when an object is rotated out (and can subtract various metrics from sum buckets)
  - One called when an object is rotated in (and can add various metrics to sum buckets)
- When an existing object is update (ie, order changes cost category), the original (non-updated) object should be subtracted, and the new updated object should be added in.
- Need some generic implementation of sum buckets by some key/type:
  - Company it would be the key
  - Type might be product inventory costs, labor hours, etc
  - Each sum bucket needs a count
- When calculating costs, all we need are the sum buckets (totals, counts)

~~NOTE: I haven't verified the algorithm can only work with bucketed sums, need to review it first.~~

Verified! Let's do this...

----

I need to figure out what exactly is the holdup. Contenders:

- Pulling out incoming/outgoing orders
- Running the orders through the algorithm
- Storing the costs for each product

## TODO

- [x] Add millisecond timestamps to various parts of `calculate_product_costs()` to figure out the biggest offenders
- [x] Once benchmark is done, focus efforts on reducing call expense
- [x] Idea? Instead of storing full, duplicate orders _in the index_ what if we just store the metrics we need on a rolling basis, such that when we add a new order, we can pre-cache some generated values or something?
- [x] If needed, only call `calculate_product_costs()` on order creation
  - [x] Should be called *after* entering the order (thus the costs to the order creator are accurate)
  - [x] Only call it for the company _receiving_ the order. It might be important at some point to keep costs more up to date, but for now I think the best trade off is to only update costs for a company directly after a new order arrives

## Notes

My guess is it's some combination, but what I really think is happening is that when we grab the recent incoming/outgoing orders, we do so via a map that's stored in a table. We pull that map out, grab the entries, and for each entry, go out and grab the order data. So there might be 200 orders, and we loop over the list and grab them one by one. Need to find a way to optimize this. 

Ideas/notes:

- A cache is feasible with a small number of participants, but at scale is useless
- Might have to store full order objects in the rolling index instead of order ids
  - obvis requires updating in both places when an order is updated
- Only generate product costs *just before and order is created*, and only for the company receiving the order?
- Instead of benchmarking, print out timestamps with run numbers (aka poor-(wo)man's benchmark)

**Comment by orthecreedence** [comment]
mentioned in commit basis@985c304f139e9cdd5f8bb1f156570a15c3958d46

**Comment by orthecreedence** [comment]
Yeah, as thought, the biggest offender by far is pulling the incoming orders, the longest call being 455ms (yikes) to pull out 300+ orders. This seems to be the case with others, pulling out labor takes a decent percentage as well.

This says to me that we need to figure out better ways of indexing (or rather, pulling out indexed) data. Maybe storing duplicates is the way to go, or maybe there's another way.

**Comment by orthecreedence** [comment]
Ok, storing the entire order object in the index (instead of just the ID) is about 4x faster, but not an order of magnitude like I'd hoped. Maybe the idea of storing a rolling set of pre-calculated ain't so bad. Will investigate further.

**Comment by orthecreedence** [comment]
Updated the costs algorithm to only run on order creation. Great, now getting a "Product is missing costs" error for all the orders. Damn it. Maybe we run all the old product costs stuff, but only do it if we have less than 10 orders or something.

**Comment by orthecreedence** [comment]
Idea: cache the last time costs were calculated (by company id) and only allow calculations every 24h.

**Comment by orthecreedence** [comment]
The cache helps, but we're still seeing 400ms+ cost generation times. This is with storing the whole order in the rolling "index" and also only generating costs once per 24h. Note that we get about 3-4x more mileage from these changes before the system starts to fail, but it still seems like we're pushing the limits here. I wonder if storing the orders in one k/v pair per-company (as opposed to using a MapIndex and iterating it) would give a perf boost...

**Comment by orthecreedence** [comment]
Stupid time. Turns out the harsh benchmarks were because the blockchain was running on virtualbox which has abysmal disk performance. I had to do this because I couldn't get it running on windows. Well, now it's magically running on windows again (???) so after some testing, looks like my changes are making a huge difference and the system can run continuously until it crashes because BEN SHAPIRO DESTROYS ROCKSDB RUNNING ON WINDOWS.

So runs fine on linux vm with terrible performance, or runs buggily on windows with great performance. Annoying.

**Comment by orthecreedence** [comment]
Just a note, running Basis on a ramdisk (linux) did eventually crash with high transaction times, so disk performance is not the issue here. Added more notes above on some ideas for going forward (going to try the pre-generated metrics approach).

**Comment by orthecreedence** [comment]
Ok, just reviews the costs algo, and it looks like the sum-buckets concept will work...exciting. It's also cool because if we need to change these later on, they can be versioned and regenerated if needed based on the rolling data the aggregate over.

In other words, these are future proof, assuming the cost algorithms of the future only rely on sums and averages.

One thing I want to do is to split `Costs::calculate_costs()` into two functions: one, with the original API that takes orders, amortization, products, etc and a new one that takes our various sum buckets. The original api function will *call* the new one once it derives its own sum buckets.

**Comment by orthecreedence** [comment]
Getting close on this, but a problem I want to document because I keept discovering it then forgetting it (too much time between chances to sit down and fix):

- Order 1 entered
- Order 1 finalized
  - Order 1 added to rolling index
- Order 2 entered (N days after Order 1)
- Order 1 rolled out of rolling index
- Order 1 edited
  - Order 1 removed from rolling index <-- oh no! error happens here!!!!1
  - Order 1 re-added to rolling index

In the above, Order 1 is double-removed from the rolling index.

Need to test if Order 1 has been rolled out of index before doing any ops on it. This means storing the *latest* date for the index somewhere and seeing if Order 1's date is older than `latest - cutoff` (ie, rolled out) before operating on it.

**Comment by orthecreedence** [comment]
^ ok, this is solved, one step closer...

**Comment by orthecreedence** [comment]
COOL got aggregate tracking implemented in https://gitlab.com/basis-/basis/commit/6c0ff9a279fe7938bc208b297ec477246eca8ef7. Now ust have to implement them by pulling the aggregate cost buckets out and shoveling them into the second half of the costs algo.

**Comment by orthecreedence** [comment]
Done :100: :100: :smile: 

The costs algorithm flies now, and side-by-side comparisons show it as deriving 1:1 the same costs as calculating from raw orders.

Note that there still seems to be some discrepancies in pricing via the simulator, but that could very likely be an issue in the simulator as opposed to the cost algo, and either way, would be outside the perview of this issue.

**Comment by orthecreedence** [comment]
closed
